[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["rt", "macros", "rt-multi-thread"] }
axum = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

tower-http = { workspace = true }

# Config management
config = "0.15"
# serde
serde = { workspace = true }

server = { path = "../server" }

[dev-dependencies]
pretty_assertions = "1"
