[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
# API
axum = { workspace = true }
utoipa = { version = "5", features = ["axum_extras", "chrono", "uuid"] }
# log
tracing = { workspace = true }
# serde
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"

# cors and static content
tower-http = { workspace = true }

# database
sea-orm = { version = "1.0", features = ["runtime-tokio-rustls", "sqlx-sqlite"] }
sea-orm-migration = "1.0"

# election
stv-rs = "0.5.1"

# utilities
uuid = { version = "1.0", features = ["v4", "serde"] }
async-trait = "0.1"
chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros", "rt-multi-thread"] }
pretty_assertions = "1"
axum-test = "17"
test-log = {version = "0.2", features = ["trace"]}
reqwest = {version = "*", features = ["blocking"]}
migration = { path = "./migration" }
